---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: minio
  title: Minio
  description: S3-compatible object storage
spec:
  type: service
  owner: group:default/storage-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgresql
  title: PostgreSQL
  namespace: postgresql15
  description: Core PostgreSQL database
  annotations:
    argocd/app-name: postgresql15
    backstage.io/kubernetes-namespace: postgresql15
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=postgresql15
spec:
  type: service
  owner: group:default/db-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
    - component:default/minio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: consul
  title: Consul
  namespace: consul
  description: Distributed data store
  annotations:
    argocd/app-name: consul
    backstage.io/kubernetes-namespace: consul
    backstage.io/kubernetes-label-selector: app=consul
spec:
  type: service
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
    - component:default/minio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vault
  title: Vault
  namespace: vault
  description: Secure secret store and PKI
  annotations:
    argocd/app-name: vault
    backstage.io/kubernetes-namespace: vault
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=vault
spec:
  type: service
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:consul/consul