---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: minio
  title: Minio
  description: S3-compatible object storage
  links:
    - title: Minio
      url: https://minio.home.lan
      icon: dashboard
spec:
  type: service
  system: default/synology
  owner: group:default/storage-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loki
  title: Loki
  description: Log aggregation and search
spec:
  type: service
  system: default/synology
  owner: group:default/storage-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgresql
  title: PostgreSQL
  namespace: postgresql15
  description: Core PostgreSQL database
  annotations:
    argocd/app-name: postgresql15
    backstage.io/kubernetes-namespace: postgresql15
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=postgresql15
spec:
  type: service
  system: default/k3s
  owner: group:default/db-admin
  lifecycle: production
  dependsOn:
    - component:synology-csi/synology-csi
    - component:default/minio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: consul
  title: Consul
  namespace: consul
  description: Distributed data store
  links:
    - url: https://consul.home.lan
      title: Consul
      icon: dashboard
  annotations:
    argocd/app-name: consul
    backstage.io/kubernetes-namespace: consul
    backstage.io/kubernetes-label-selector: app=consul
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
    - component:default/minio
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vault
  title: Vault
  namespace: vault
  description: Secure secret store and PKI
  links:
    - url: https://vault.home.lan
      title: Vault
      icon: dashboard
  annotations:
    argocd/app-name: vault
    backstage.io/kubernetes-namespace: vault
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=vault
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:consul/consul
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: authentik
  title: Authentik
  namespace: authentik
  description: Single-Sign On Provider
  links:
    - url: https://authentik.home.lan
      title: Authentik
      icon: dashboard
  annotations:
    argocd/app-name: authentik
    backstage.io/kubernetes-namespace: authentik
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=authentik
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:postgresql15/postgresql
    - component:vault/vault
    - component:redis/redis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: n8n
  title: N8N
  namespace: n8n
  description: Low-code automation
  links:
    - url: https://n8n.home.lan
      title: N8n
      icon: dashboard
  annotations:
    argocd/app-name: n8n
    backstage.io/kubernetes-namespace: n8n
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=n8n
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:postgresql15/postgresql
    - component:vault/vault
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redis
  title: Redis
  namespace: redis
  description: Persistent cache
  annotations:
    argocd/app-name: redis
    backstage.io/kubernetes-namespace: redis
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=redis
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus-operator
  title: Prometheus Operator
  namespace: prometheus
  description: Time-scale database for metrics
  links:
    - url: https://prom.home.lan
      title: Prometheus
      icon: dashboard
    - url: https://alertmanager.home.lan
      title: Alert Manager
      icon: dashboard
  annotations:
    argocd/app-name: prometheus-operator
    backstage.io/kubernetes-namespace: prometheus
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=prometheus-operator
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:synology-csi/synology-csi
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: promtail
  title: Promtail
  namespace: promtail
  description: Log shipping to Loki
  annotations:
    argocd/app-name: promtail
    backstage.io/kubernetes-namespace: monitoring
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=promtail
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:default/loki
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: semaphore
  title: Ansible Semaphore
  namespace: semaphore
  description: Ansible job runner and scheduler
  links:
    - url: https://ansible.home.lan
      title: Ansible Semaphore
      icon: dashboard
  annotations:
    argocd/app-name: semaphore
    backstage.io/kubernetes-namespace: semaphore
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=semaphore
    # grafana/alert-label-selector: 
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:postgresql15/postgresql
    - component:vault/vault
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: harbor
  title: Harbor
  namespace: harbor
  description: Container image management
  links:
    - url: https://harbor.home.lan
      title: Harbor
      icon: dashboard
  annotations:
    argocd/app-name: harbor
    backstage.io/kubernetes-namespace: harbor
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=harbor
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - component:postgresql15/postgresql
    - component:vault/vault
    - component:redis/redis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: protonmail-bridge
  title: Protonmail Bridge
  namespace: protonmail-bridge
  description: Email service for Protonmail
  annotations:
    argocd/app-name: protonmail-bridge
    backstage.io/kubernetes-namespace: protonmail-bridge
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=protonmail-bridge
spec:
  type: service
  system: default/k3s
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: certmanager
  title: Cert Manager
  namespace: certmanager
  description: Cert management and issuance
  annotations:
    argocd/app-name: cert-manager
    backstage.io/kubernetes-namespace: cert-manager
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=cert-manager
spec:
  type: service
  system: default/k3s-internals
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: descheduler
  title: Descheduler
  namespace: descheduler
  description: Rebalance workloads across the cluster
  annotations:
    argocd/app-name: descheduler
    backstage.io/kubernetes-namespace: descheduler
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=descheduler
spec:
  type: service
  system: default/k3s-internals
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-dns
  title: External DNS
  namespace: external-dns
  description: Manage DNS records
  annotations:
    argocd/app-name: external-dns
    backstage.io/kubernetes-namespace: kube-system
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=external-dns
spec:
  type: service
  system: default/k3s-internals
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - resource:default/router
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx
  title: Nginx Ingress Controller
  namespace: nginx
  description: Ingress & Load Balancer
  annotations:
    backstage.io/kubernetes-namespace: nginx
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=ingress-nginx
spec:
  type: service
  system: default/k3s-internals
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: synology-csi
  title: Synology CSI
  namespace: synology-csi
  description: Synology container storage interface
  annotations:
    backstage.io/kubernetes-namespace: synology-csi
    backstage.io/kubernetes-label-selector: app=synology-csi-node
spec:
  type: service
  system: default/k3s-internals
  owner: group:default/k8s-admin
  lifecycle: production
  dependsOn:
    - resource:default/nas