nodeLinker: node-modules

packageExtensions:
  "@backstage/backend-common@*":
    dependencies:
      "@backstage/backend-tasks": "*"
      "@backstage/plugin-app-backend": "*"
      "@backstage/plugin-auth-backend": "*"
      "@backstage/plugin-catalog-backend": "*"
      "@backstage/plugin-scaffolder-backend": "*"
      app: "*"
  "@backstage/cli@*":
    dependencies:
      "@jest-environment-node": "*"
  "@graphiql/toolkit@*":
    dependencies:
      graphql-ws: "*"
  express-openapi-validator@*:
    dependencies:
      express: "*"
  knex@*:
    dependencies:
      better-sqlite3: "*"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-4.4.1.cjs
