nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.0.2.cjs

pnpFallbackMode: all

packageExtensions:
  "@backstage/core-components@*":
    dependencies:
      "react-router-dom": "*"
      "react-dom": "*"
  "@backstage/core-plugin-api@*":
    dependencies:
      "react-router-dom": "*"
      "react-dom": "*"
  "@material-ui/core@*":
    dependencies:
      "react-dom": "*"
  "@apidevtools/json-schema-ref-parser@*":
    dependencies:
      "process": "*"
  "@asyncapi/parser@*":
    dependencies:
      "process": "*"
  "@azure/core-util@*":
    dependencies:
      "process": "*"
  "@azure/identity@*":
    dependencies:
      "process": "*"
  "@azure/logger@*":
    dependencies:
      "process": "*"
  "avsc@*":
    dependencies:
      "process": "*"
  "browserify-zlib@*":
    dependencies:
      "process": "*"
  "call-me-maybe@*":
    dependencies:
      "process": "*"
  "dataloader@*":
    dependencies:
      "process": "*"
  "jszip@*":
    dependencies:
      "process": "*"
  "process-nextick-args@*":
    dependencies:
      "process": "*"
  "readable-stream@*":
    dependencies:
      "process": "*"
  "universal-user-agent@*":
    dependencies:
      "process": "*"
  "util@*":
    dependencies:
      "process": "*"
  "lru-cache@*":
    dependencies:
      "process": "*"
  "yaml-npm@*":
    dependencies:
      "process": "*"
  "yaml@*":
    dependencies:
      "process": "*"
  "framer-motion@*":
    dependencies:
      "process": "*"