nodeLinker: node-modules

# packageExtensions:
#   "@backstage/cli@*":
#     dependencies:
#       "@jest-environment-node": "*"
#   "@graphiql/toolkit@*":
#     dependencies:
#       graphql-ws: "*"
#   express-openapi-validator@*:
#     dependencies:
#       express: "*"
#   knex@*:
#     dependencies:
#       better-sqlite3: "*"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-4.5.1.cjs
