nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.0.2.cjs

pnpFallbackMode: all

packageExtensions:
  "@graphiql/toolkit@*":
    dependencies:
      "graphql-ws": "*"
  "@backstage/cli@*":
    dependencies:
      "@jest-environment-node": "*"
  "@backstage/backend-common@*":
    dependencies:
      "@backstage/plugin-app-backend": "*"
      "@backstage/plugin-auth-backend": "*"
      "@backstage/plugin-scaffolder-backend": "*"
      "@backstage/plugin-catalog-backend": "*"
      "@backstage/backend-tasks": "*"
      "app": "*"
  "express-openapi-validator@*":
    dependencies:
      "express": "*"
  "@octokit/plugin-retry@*":
    dependencies:
      "@octokit/request-error": "*"
  "knex@*":
    dependencies:
      "better-sqlite3": "*"