---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: k8s-admin
  namespace: default
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: k3s
  namespace: default
spec:
  owner: group:default/k8s-admin